### ISSUE TITLE
Unknow : throws BlacklistedException

### ISSUE THREAD

**Issue by Flynrod** [timbru31/spigot-anti-piracy-backend#147]
Here's a problem : http://prntscr.com/etj5rh
How do I start the check in the main class ?

**Comment by timbru31** [comment]
Call the blacklistCheck method?

**Comment by Flynrod** [comment]
Thank you for the quick reply. How can I do to trigger checking with my main class for it to give ID, etc ...

**Comment by timbru31** [comment]
I expect that you have basic knowledge of Java? It's a class, so create a new instance, call the method on it. Regarding the user ID of the buyer, refer to this post: https://www.spigotmc.org/threads/anti-piracy.108864/page-2#post-1188884

**Comment by timbru31** [comment]
Did this solve your problem?

**Comment by timbru31** [comment]
Closing, if you have further questions please comment.
