### ISSUE TITLE
Only the last license id the banned_users.txt file is blacklisted

### ISSUE THREAD

**Issue by Exeton** [timbru31/spigot-anti-piracy-backend#211]
I'm not sure if I'm doing something wrong, however I can only get the last user in the banned_users txt file to work.

**Comment by timbru31** [comment]
Can you provide some more information please?
-Node.js version
- OS
- spigot-anti-piracy-backend version

This helps me narrow down the issue.

**Comment by Exeton** [comment]
Node 8.10.0
Windows 10 Enterprise Edition
I think I'm using the latest version. I ran npm install -g spigot-anti-piracy-backend. This was either today or yesterday.

**Comment by Exeton** [comment]
This is what my banned_users file looks like (The second entry is the license key which causing trouble)
C7524DG643288DA13AC865A498751235
Test

**Comment by timbru31** [comment]
Can you try to install the latest git version? (npm i -g https://github.com/timbru31/spigot-anti-piracy-backend.git) - I've recently fixed newline detection to handle Windows line breaks, too.

**Comment by Exeton** [comment]
Node is giving me an error. https://pastebin.com/FZUW75hw
I tried getting the zip from github. But Node throws an error about ts files.

**Comment by timbru31** [comment]
Oh yes, it's of course not working out of the box from GitHub because of .ts files. I've published v1.0.3, can you give it a try please?

**Comment by Exeton** [comment]
npm install -g spigot-anti-piracy-backend is still giving me a app.ts file
https://pastebin.com/tZ3vyVtw

Also. Thanks for getting back so fast.

**Comment by timbru31** [comment]
Oh you are cd'ing into the directory and then run the app?
In this case, instead of running `npm start` use `node dist/app.js` - to use it anywhere you could use `npx spigot-anti-piracy-backend`

**Comment by Exeton** [comment]
Hmm. Now only the first license is working for me.

**Comment by timbru31** [comment]
Can you upload an example of your blacklisted users file? (not pastebin.com please, so the linebreaks are preserved as is).
Thanks in advance!

**Comment by Exeton** [comment]
[Users.txt](https://github.com/timbru31/spigot-anti-piracy-backend/files/1849335/Users.txt)

**Comment by timbru31** [comment]
I've published v1.1.0 which fixes your issue. Let me know if it (finally) works.

**Comment by Exeton** [comment]
It works! Also, thanks a ton for making this project :P
